[tool.basedpyright]
reportUnusedCallResult = false
reportMissingTypeStubs = false
reportUnusedImport = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownParameterType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnannotatedClassAttribute = false
reportImplicitOverride = false
reportMissingParameterType = false
